--CREACION TABLA USUARIO
CREATE TABLE USUARIO (
		idusuario      VARCHAR(10)  NOT NULL, 
		nick           VARCHAR(45)  NOT NULL,
		password       VARCHAR(50)  NOT NULL,
		CONSTRAINT usu_pk_idu PRIMARY KEY (idusuario)
);

--CREACION TABLA GRUPO
CREATE TABLE GRUPO (
		idgrupo        INT           NOT NULL AUTO_INCREMENT, 
		nombre         VARCHAR(50)  NOT NULL,
		CONSTRAINT gru_pk_idg PRIMARY KEY (idgrupo)
);

--CREACION TABLA MENSAJE
CREATE TABLE MENSAJE (
		idmensaje      INT   	     NOT NULL AUTO_INCREMENT, 
		cadena         VARCHAR(255) NOT NULL,
		destinatario   VARCHAR(2)       NOT NULL,
		fecha          TIMESTAMP     NOT NULL,
		idusuario      VARCHAR(10)  NOT NULL,
		CONSTRAINT men_pk_idm PRIMARY KEY (idmensaje)
);

--CREACION TABLA USUARIO_GRUPO
CREATE TABLE USUARIO_GRUPO (
	idgrupo      	 INT   		NOT NULL,
	idusuario      	 VARCHAR(10)   NOT NULL,
	idmensaje      	 INT		NOT NULL
);

--REGLAS DE NEGOCIO TABLA USUARIO
ALTER TABLE MENSAJE ADD(
	ADD UNIQUE INDEX 'nick_UNIQUE' ('nick' ASC) ;
);

--REGLAS DE NEGOCIO TABLA MENSAJE
ALTER TABLE MENSAJE ADD(
	CONSTRAINT men_fk_idu FOREIGN KEY (idusuario) REFERENCES USUARIO(idusuario),
);

--REGLAS DE NEGOCIO TABLA GRUPO
ALTER TABLE MENSAJE ADD(
	ADD UNIQUE INDEX 'nombre_UNIQUE' ('nombre' ASC) ;
);

--REGLAS DE NEGOCIO TABLA USUARIO_GRUPO
ALTER TABLE USUARIO_GRUPO ADD(
	CONSTRAINT usug_fk_idg FOREIGN KEY (idgrupo) REFERENCES GRUPO(idgrupo),
	CONSTRAINT usug_fk_idu FOREIGN KEY (idusuario) REFERENCES USUARIO(idusuario),
CONSTRAINT usug_fk_idm FOREIGN KEY (idmensaje) REFERENCES MENSAJE(idmensaje)
);